#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

# creates a symbolic link (-s option) between the Nginx configuration file
# and th enabled sites directory
ln -sf /etc/nginx/sites-avilable/defualt /etc/nginx/sites-enabled/defualt
# restart nginx
service nginx start
# terminates the first nginx process ID
kill "$(pgrep 'nginx' | head -1)"
